apiVersion: v1
kind: Service
metadata:
  name: eth2-prysm-beacon-p2p-svc
spec:
  type: NodePort
  ports:
  - port: 30876
    targetPort: 30876
    nodePort: 30876
    protocol: TCP
    name: p2p
  selector:
    app: eth2-prysm-beacon
