apiVersion: v1
kind: Service
metadata:
  name: eth2-prysm-beacon-svc
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: eth2-prysm-beacon
