apiVersion: v1
kind: Service
metadata:
  name: eth2-geth-execution-svc
spec:
  type: NodePort
  ports:
  - port: 8551
    targetPort: 8551
    protocol: TCP
    name: http
  selector:
    app: eth2-geth-execution
